spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_library?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

books:
  upload:
    path: C:\Users\User\IdeaProjects\onlineLibrary\upload
